# Render.com deployment configuration for LL&L Futures Frontend

# Build Command
npm install && npm run build

# Publish Directory
dist

# Node Version
18

# Environment Variables (set these in Render dashboard)
# VITE_API_URL=https://your-backend-app-name.onrender.com/api
